# Generated by Django 4.0.3 on 2022-03-19 09:33

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('profiles', '0004_rename_friendlist_connectionlist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ConnectionList',
            new_name='Connection',
        ),
    ]
